#ifndef _ROACHTX_CONF_HW_H_
#define _ROACHTX_CONF_HW_H_

#include "roachtx_conf.h"

#define ROACHHW_PIN_I2C_SCL    23
#define ROACHHW_PIN_I2C_SDA    22

#define ROACHHW_PIN_BTN_UP     12
#define ROACHHW_PIN_BTN_DOWN   10
#define ROACHHW_PIN_BTN_LEFT   11
#define ROACHHW_PIN_BTN_RIGHT  9
#define ROACHHW_PIN_BTN_CENTER 13
#define ROACHHW_PIN_BTN_G5     24
#define ROACHHW_PIN_BTN_G6     1
#define ROACHHW_PIN_BTN_SW1    18
#define ROACHHW_PIN_BTN_WEAP   ROACHHW_PIN_BTN_SW1
#define ROACHHW_PIN_BTN_SW2    19
#define ROACHHW_PIN_BTN_SW3    26
#define ROACHHW_PIN_BTN_SW4    25
#define ROACHHW_PIN_BTN_D7     7

#define ROACHHW_PIN_POT_THROTTLE A0
#define ROACHHW_PIN_POT_STEERING A1
#define ROACHHW_PIN_POT_WEAPON   A2
#define ROACHHW_PIN_POT_AUX      A3
#define ROACHHW_PIN_POT_BATTERY  A6

#define ROACHHW_PIN_ENC_A  5
#define ROACHHW_PIN_ENC_B  6

#define ROACHHW_PIN_FEM_TX  2
#define ROACHHW_PIN_FEM_RX  0

#define ROACHHW_PIN_LED_RED  3
#define ROACHHW_PIN_LED_BLU  4
#define ROACHHW_PIN_LED_NEO  8

#define SCREEN_ADDRESS 0x3C

#endif
